"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ADMIN_CONFIG = exports.COLONIZATION_CONFIG = exports.TRANSPORT_CONFIG = exports.HAPPINESS_CONFIG = exports.POPULATION_CONFIG = exports.RESEARCH_CONFIG_PLACEHOLDER = exports.BUILDING_UPGRADE_CONFIG = exports.BUILDING_TYPES = exports.BUILDING_DISPLAY_CONFIG = exports.BUILDING_CONFIG = exports.STORAGE_CONFIG = exports.RESOURCE_PRODUCTION_CONFIG = exports.RESOURCE_TYPES = exports.RESOURCE_LABELS = exports.MAP_CONFIG = exports.DEFAULT_WORLD_CONFIG = void 0;
var world_config_js_1 = require("./world.config.js");
Object.defineProperty(exports, "DEFAULT_WORLD_CONFIG", { enumerable: true, get: function () { return world_config_js_1.DEFAULT_WORLD_CONFIG; } });
var map_config_js_1 = require("./map.config.js");
Object.defineProperty(exports, "MAP_CONFIG", { enumerable: true, get: function () { return map_config_js_1.MAP_CONFIG; } });
var resources_config_js_1 = require("./resources.config.js");
Object.defineProperty(exports, "RESOURCE_LABELS", { enumerable: true, get: function () { return resources_config_js_1.RESOURCE_LABELS; } });
Object.defineProperty(exports, "RESOURCE_TYPES", { enumerable: true, get: function () { return resources_config_js_1.RESOURCE_TYPES; } });
Object.defineProperty(exports, "RESOURCE_PRODUCTION_CONFIG", { enumerable: true, get: function () { return resources_config_js_1.RESOURCE_PRODUCTION_CONFIG; } });
Object.defineProperty(exports, "STORAGE_CONFIG", { enumerable: true, get: function () { return resources_config_js_1.STORAGE_CONFIG; } });
var buildings_config_js_1 = require("./buildings.config.js");
Object.defineProperty(exports, "BUILDING_CONFIG", { enumerable: true, get: function () { return buildings_config_js_1.BUILDING_CONFIG; } });
Object.defineProperty(exports, "BUILDING_DISPLAY_CONFIG", { enumerable: true, get: function () { return buildings_config_js_1.BUILDING_DISPLAY_CONFIG; } });
Object.defineProperty(exports, "BUILDING_TYPES", { enumerable: true, get: function () { return buildings_config_js_1.BUILDING_TYPES; } });
Object.defineProperty(exports, "BUILDING_UPGRADE_CONFIG", { enumerable: true, get: function () { return buildings_config_js_1.BUILDING_UPGRADE_CONFIG; } });
var research_config_js_1 = require("./research.config.js");
Object.defineProperty(exports, "RESEARCH_CONFIG_PLACEHOLDER", { enumerable: true, get: function () { return research_config_js_1.RESEARCH_CONFIG_PLACEHOLDER; } });
var population_config_js_1 = require("./population.config.js");
Object.defineProperty(exports, "POPULATION_CONFIG", { enumerable: true, get: function () { return population_config_js_1.POPULATION_CONFIG; } });
var happiness_config_js_1 = require("./happiness.config.js");
Object.defineProperty(exports, "HAPPINESS_CONFIG", { enumerable: true, get: function () { return happiness_config_js_1.HAPPINESS_CONFIG; } });
var transport_config_js_1 = require("./transport.config.js");
Object.defineProperty(exports, "TRANSPORT_CONFIG", { enumerable: true, get: function () { return transport_config_js_1.TRANSPORT_CONFIG; } });
var colonization_config_js_1 = require("./colonization.config.js");
Object.defineProperty(exports, "COLONIZATION_CONFIG", { enumerable: true, get: function () { return colonization_config_js_1.COLONIZATION_CONFIG; } });
var admin_config_js_1 = require("./admin.config.js");
Object.defineProperty(exports, "ADMIN_CONFIG", { enumerable: true, get: function () { return admin_config_js_1.ADMIN_CONFIG; } });
