export const QUEST_TRIGGERS = {
  CITY_DASHBOARD_OPENED: 'city_dashboard_opened',
  RESOURCES_VIEWED: 'resources_viewed',
  WORKER_ASSIGNMENT_UPDATED: 'worker_assignment_updated',
  BUILDING_UPGRADE_STARTED: 'building_upgrade_started',
  BUILDING_UPGRADE_COMPLETED: 'building_upgrade_completed',
  ACADEMY_LEVEL_REACHED: 'academy_level_reached',
  SCIENTISTS_ASSIGNED: 'scientists_assigned',
  RESEARCH_STARTED: 'research_started',
  RESEARCH_COMPLETED: 'research_completed',
  CITY_HALL_LEVEL_REACHED: 'city_hall_level_reached',
  WORLD_MAP_OPENED: 'world_map_opened',
  CITY_BUILDING_CLICKED: 'city_building_clicked',
  PORT_LEVEL_REACHED: 'port_level_reached',
  RESOURCE_TRANSPORT_STARTED: 'resource_transport_started',
  RESOURCE_TRANSPORT_COMPLETED: 'resource_transport_completed',
} as const;

export type QuestTrigger = (typeof QUEST_TRIGGERS)[keyof typeof QUEST_TRIGGERS];

export type QuestRewards = {
  resources?: Partial<Record<'wood' | 'gold', number>>;
  researchPoints?: number;
};

export type TutorialQuestDefinition = {
  id: string;
  order: number;
  type: 'tutorial';
  title: string;
  description: string;
  objectiveLabel: string;
  trigger: QuestTrigger;
  target: number;
  rewards: QuestRewards;
  payloadMatch?: Record<string, unknown>;
};

export const TUTORIAL_QUESTS: TutorialQuestDefinition[] = [
  {
    id: 'welcome_city',
    order: 1,
    type: 'tutorial',
    title: 'Welcome to Your City',
    description: 'This is your first island city. Review your city overview to begin.',
    objectiveLabel: 'Open the city dashboard',
    trigger: QUEST_TRIGGERS.CITY_DASHBOARD_OPENED,
    target: 1,
    rewards: { resources: { wood: 50, gold: 25 } },
  },
  {
    id: 'check_resources',
    order: 2,
    type: 'tutorial',
    title: 'Check Your Resources',
    description: 'Resources are produced over time and used to grow your city.',
    objectiveLabel: 'View the resource bar',
    trigger: QUEST_TRIGGERS.RESOURCES_VIEWED,
    target: 1,
    rewards: { resources: { wood: 50 } },
  },
  {
    id: 'assign_citizens',
    order: 3,
    type: 'tutorial',
    title: 'Assign Your Citizens',
    description: 'Citizens can work to produce resources or research knowledge.',
    objectiveLabel: 'Update worker assignment at least once',
    trigger: QUEST_TRIGGERS.WORKER_ASSIGNMENT_UPDATED,
    target: 1,
    rewards: { resources: { wood: 75, gold: 25 } },
  },
  {
    id: 'upgrade_warehouse',
    order: 4,
    type: 'tutorial',
    title: 'Upgrade the Warehouse',
    description: 'The Warehouse increases how many resources your city can store.',
    objectiveLabel: 'Start a Warehouse upgrade',
    trigger: QUEST_TRIGGERS.BUILDING_UPGRADE_STARTED,
    target: 1,
    rewards: { resources: { wood: 100 } },
    payloadMatch: { buildingType: 'warehouse' },
  },
  {
    id: 'complete_construction',
    order: 5,
    type: 'tutorial',
    title: 'Complete Your First Construction',
    description: 'Building upgrades take time and continue while you are offline.',
    objectiveLabel: 'Complete any building upgrade',
    trigger: QUEST_TRIGGERS.BUILDING_UPGRADE_COMPLETED,
    target: 1,
    rewards: { resources: { wood: 100, gold: 50 } },
  },
  {
    id: 'build_academy',
    order: 6,
    type: 'tutorial',
    title: 'Build the Academy',
    description: 'The Academy allows citizens to become scientists and generate research points.',
    objectiveLabel: 'Build or upgrade Academy to level 1',
    trigger: QUEST_TRIGGERS.ACADEMY_LEVEL_REACHED,
    target: 1,
    rewards: { resources: { wood: 75, gold: 75 } },
  },
  {
    id: 'assign_scientists',
    order: 7,
    type: 'tutorial',
    title: 'Assign Scientists',
    description: 'Scientists generate research points used to unlock technologies.',
    objectiveLabel: 'Assign at least 1 scientist',
    trigger: QUEST_TRIGGERS.SCIENTISTS_ASSIGNED,
    target: 1,
    rewards: { researchPoints: 25 },
  },
  {
    id: 'start_research',
    order: 8,
    type: 'tutorial',
    title: 'Start Your First Research',
    description: 'Research unlocks long-term progress for your empire.',
    objectiveLabel: 'Start any technology research',
    trigger: QUEST_TRIGGERS.RESEARCH_STARTED,
    target: 1,
    rewards: { researchPoints: 25 },
  },
  {
    id: 'complete_research',
    order: 9,
    type: 'tutorial',
    title: 'Complete Your First Research',
    description: 'Completed technologies prepare your empire for future systems.',
    objectiveLabel: 'Complete any technology research',
    trigger: QUEST_TRIGGERS.RESEARCH_COMPLETED,
    target: 1,
    rewards: { resources: { wood: 150, gold: 100 } },
  },
  {
    id: 'prepare_for_world',
    order: 10,
    type: 'tutorial',
    title: 'Prepare for the World',
    description: 'Your city is growing. Soon you will discover the islands around you.',
    objectiveLabel: 'Reach City Hall level 2',
    trigger: QUEST_TRIGGERS.CITY_HALL_LEVEL_REACHED,
    target: 1,
    rewards: { resources: { wood: 200, gold: 100 } },
  },
  {
    id: 'discover_world_map',
    order: 11,
    type: 'tutorial',
    title: 'Discover the World Map',
    description: 'Your city is only one part of a larger island world. Open the World Map to see nearby islands.',
    objectiveLabel: 'Open the World Map',
    trigger: QUEST_TRIGGERS.WORLD_MAP_OPENED,
    target: 1,
    rewards: { resources: { wood: 100, gold: 50 } },
  },
  {
    id: 'explore_city',
    order: 12,
    type: 'tutorial',
    title: 'Explore Your City',
    description: 'Your city is now interactive. Click on a building to inspect it and manage upgrades.',
    objectiveLabel: 'Open any building in the city view',
    trigger: QUEST_TRIGGERS.CITY_BUILDING_CLICKED,
    target: 1,
    rewards: { resources: { wood: 75, gold: 25 } },
  },
  {
    id: 'inspect_warehouse',
    order: 13,
    type: 'tutorial',
    title: 'Inspect the Warehouse',
    description: 'The Warehouse controls how many resources your city can store.',
    objectiveLabel: 'Open the Warehouse in the city view',
    trigger: QUEST_TRIGGERS.CITY_BUILDING_CLICKED,
    target: 1,
    rewards: { resources: { wood: 50 } },
    payloadMatch: { buildingType: 'warehouse' },
  },
  {
    id: 'build_port',
    order: 14,
    type: 'tutorial',
    title: 'Build a Port',
    description: 'The Port connects your cities and unlocks internal resource transport.',
    objectiveLabel: 'Build or upgrade Port to level 1',
    trigger: QUEST_TRIGGERS.PORT_LEVEL_REACHED,
    target: 1,
    rewards: { resources: { wood: 100, gold: 50 } },
  },
  {
    id: 'start_resource_transport',
    order: 15,
    type: 'tutorial',
    title: 'Send Resources',
    description: 'Use the Transport screen to send resources from one city to another.',
    objectiveLabel: 'Start a resource transport',
    trigger: QUEST_TRIGGERS.RESOURCE_TRANSPORT_STARTED,
    target: 1,
    rewards: { resources: { wood: 100 } },
  },
  {
    id: 'complete_resource_transport',
    order: 16,
    type: 'tutorial',
    title: 'Complete a Delivery',
    description: 'Resource transports arrive after their travel timer finishes.',
    objectiveLabel: 'Complete a resource transport',
    trigger: QUEST_TRIGGERS.RESOURCE_TRANSPORT_COMPLETED,
    target: 1,
    rewards: { resources: { gold: 100 } },
  },
];
