export const RESEARCH_PRODUCTION_CONFIG = {
  researchPerScientistPerHour: 5,
  academyBonusPerLevelAboveOne: 0.25,
} as const;

export const RESEARCH_CATEGORIES = {
  ECONOMY: 'economy',
  MILITARY: 'military',
  NAVAL: 'naval',
  CONSTRUCTION: 'construction',
  SCIENCE: 'science',
  GOVERNANCE: 'governance',
  TRADE: 'trade',
  DEFENSE: 'defense',
  LUXURY: 'luxury',
  ESPIONAGE: 'espionage',
} as const;

export type ResearchCategory = (typeof RESEARCH_CATEGORIES)[keyof typeof RESEARCH_CATEGORIES];

export const RESEARCH_TYPES = {
  IMPROVED_WOODCUTTING: 'improved_woodcutting',
  BASIC_STORAGE: 'basic_storage',
  BASIC_ARCHITECTURE: 'basic_architecture',
  BASIC_NAVIGATION: 'basic_navigation',
  BASIC_TRAINING: 'basic_training',
  BASIC_TRADE: 'basic_trade',
  CITY_PLANNING: 'city_planning',
  ACADEMIC_CURRICULUM: 'academic_curriculum',
  HARBOR_ADMINISTRATION: 'harbor_administration',
  NAVAL_ARCHITECTURE: 'naval_architecture',
  COLONIAL_BUREAUCRACY: 'colonial_bureaucracy',
  ORGANIZED_LABOR: 'organized_labor',
  TAX_RECORDS: 'tax_records',
  MARKET_EXCHANGE: 'market_exchange',
  FORMATION_TACTICS: 'formation_tactics',
  MILITARY_LOGISTICS: 'military_logistics',
  RANGED_DRILLS: 'ranged_drills',
  IRON_WEAPONS: 'iron_weapons',
  STEEL_WEAPONS: 'steel_weapons',
  MOUNTED_WARFARE: 'mounted_warfare',
  SIEGE_ENGINEERING: 'siege_engineering',
  SIEGE_LOGISTICS: 'siege_logistics',
  SHIPBUILDING: 'shipbuilding',
  COASTAL_PATROLS: 'coastal_patrols',
  LIGHT_GALLEY_HANDLING: 'light_galley_handling',
  DOCKSIDE_BOARDING: 'dockside_boarding',
  RAM_SHIP_DESIGN: 'ram_ship_design',
  FLEET_LOGISTICS: 'fleet_logistics',
  REINFORCED_HULLS: 'reinforced_hulls',
  WAR_GALLEY_DESIGN: 'war_galley_design',
  NAVAL_TACTICS: 'naval_tactics',
  NAVAL_ARTILLERY: 'naval_artillery',
  INCENDIARY_SHIPBUILDING: 'incendiary_shipbuilding',
  HEAVY_SHIPWRIGHTING: 'heavy_shipwrighting',
  STONE_MASONRY: 'stone_masonry',
  ENGINEERING_PLANS: 'engineering_plans',
  CRYSTAL_OPTICS: 'crystal_optics',
  ADMINISTRATION: 'administration',
  WALL_ENGINEERING: 'wall_engineering',
  LUXURY_REFINEMENT: 'luxury_refinement',
  COUNTERINTELLIGENCE: 'counterintelligence',
} as const;

export type TechnologyId = (typeof RESEARCH_TYPES)[keyof typeof RESEARCH_TYPES];

export type TechnologyDefinition = {
  id: TechnologyId;
  name: string;
  branch: ResearchCategory;
  category: ResearchCategory;
  tier: number;
  description: string;
  cost: number;
  durationSeconds: number;
  requirements: TechnologyId[];
  unlocks: string[];
};

export const TECHNOLOGY_CONFIG: Record<TechnologyId, TechnologyDefinition> = {
  [RESEARCH_TYPES.IMPROVED_WOODCUTTING]: {
    id: RESEARCH_TYPES.IMPROVED_WOODCUTTING,
    name: 'Improved Woodcutting',
    branch: RESEARCH_CATEGORIES.ECONOMY,
    category: RESEARCH_CATEGORIES.ECONOMY,
    tier: 1,
    description: 'Improves wood production. The bonus will be applied in a future sprint.',
    cost: 900,
    durationSeconds: 1800,
    requirements: [],
    unlocks: ['Economy upgrade conditions', 'Higher Warehouse progression'],
  },
  [RESEARCH_TYPES.BASIC_STORAGE]: {
    id: RESEARCH_TYPES.BASIC_STORAGE,
    name: 'Basic Storage',
    branch: RESEARCH_CATEGORIES.ECONOMY,
    category: RESEARCH_CATEGORIES.ECONOMY,
    tier: 1,
    description: 'Improves storage knowledge. Advanced storage bonuses will be added later.',
    cost: 900,
    durationSeconds: 1800,
    requirements: [],
    unlocks: ['Warehouse milestones', 'Larger resource stockpiles'],
  },
  [RESEARCH_TYPES.BASIC_ARCHITECTURE]: {
    id: RESEARCH_TYPES.BASIC_ARCHITECTURE,
    name: 'Basic Architecture',
    branch: RESEARCH_CATEGORIES.CONSTRUCTION,
    category: RESEARCH_CATEGORIES.CONSTRUCTION,
    tier: 1,
    description: 'Unlocks better construction planning. Construction bonuses will be added later.',
    cost: 900,
    durationSeconds: 1800,
    requirements: [RESEARCH_TYPES.IMPROVED_WOODCUTTING],
    unlocks: ['Building level 10 progression', 'Advanced construction conditions'],
  },
  [RESEARCH_TYPES.BASIC_NAVIGATION]: {
    id: RESEARCH_TYPES.BASIC_NAVIGATION,
    name: 'Basic Navigation',
    branch: RESEARCH_CATEGORIES.NAVAL,
    category: RESEARCH_CATEGORIES.NAVAL,
    tier: 1,
    description: 'Prepares the empire for ships and future expansion.',
    cost: 900,
    durationSeconds: 1800,
    requirements: [],
    unlocks: ['Port upgrades', 'Shipyard foundation'],
  },
  [RESEARCH_TYPES.BASIC_TRAINING]: {
    id: RESEARCH_TYPES.BASIC_TRAINING,
    name: 'Basic Training',
    branch: RESEARCH_CATEGORIES.MILITARY,
    category: RESEARCH_CATEGORIES.MILITARY,
    tier: 1,
    description: 'Prepares the city for basic unit training in a future sprint.',
    cost: 900,
    durationSeconds: 1800,
    requirements: [],
    unlocks: ['Barracks progression', 'Core infantry training'],
  },
  [RESEARCH_TYPES.BASIC_TRADE]: {
    id: RESEARCH_TYPES.BASIC_TRADE,
    name: 'Basic Trade',
    branch: RESEARCH_CATEGORIES.TRADE,
    category: RESEARCH_CATEGORIES.TRADE,
    tier: 1,
    description: 'Prepares the city for future marketplace and trade routes.',
    cost: 900,
    durationSeconds: 1800,
    requirements: [RESEARCH_TYPES.BASIC_NAVIGATION],
    unlocks: ['Trading Post conditions', 'Commerce upgrades'],
  },
  [RESEARCH_TYPES.CITY_PLANNING]: {
    id: RESEARCH_TYPES.CITY_PLANNING,
    name: 'City Planning',
    branch: RESEARCH_CATEGORIES.GOVERNANCE,
    category: RESEARCH_CATEGORIES.GOVERNANCE,
    tier: 1,
    description: 'Formalizes the first city expansion plan beyond basic settlement growth.',
    cost: 900,
    durationSeconds: 1800,
    requirements: [RESEARCH_TYPES.IMPROVED_WOODCUTTING],
    unlocks: ['City Hall level 3 conditions'],
  },
  [RESEARCH_TYPES.ACADEMIC_CURRICULUM]: {
    id: RESEARCH_TYPES.ACADEMIC_CURRICULUM,
    name: 'Academic Curriculum',
    branch: RESEARCH_CATEGORIES.SCIENCE,
    category: RESEARCH_CATEGORIES.SCIENCE,
    tier: 1,
    description: 'Organizes teaching methods for stronger early research output.',
    cost: 900,
    durationSeconds: 1800,
    requirements: [RESEARCH_TYPES.BASIC_STORAGE],
    unlocks: ['Academy level 2 conditions'],
  },
  [RESEARCH_TYPES.HARBOR_ADMINISTRATION]: {
    id: RESEARCH_TYPES.HARBOR_ADMINISTRATION,
    name: 'Harbor Administration',
    branch: RESEARCH_CATEGORIES.NAVAL,
    category: RESEARCH_CATEGORIES.NAVAL,
    tier: 1,
    description: 'Creates the local rules and crews needed to scale port logistics.',
    cost: 900,
    durationSeconds: 1800,
    requirements: [RESEARCH_TYPES.BASIC_NAVIGATION],
    unlocks: ['Port level 2 conditions'],
  },
  [RESEARCH_TYPES.NAVAL_ARCHITECTURE]: {
    id: RESEARCH_TYPES.NAVAL_ARCHITECTURE,
    name: 'Naval Architecture',
    branch: RESEARCH_CATEGORIES.NAVAL,
    category: RESEARCH_CATEGORIES.NAVAL,
    tier: 1,
    description: 'Introduces the construction plans needed to open a shipyard.',
    cost: 900,
    durationSeconds: 1800,
    requirements: [RESEARCH_TYPES.BASIC_NAVIGATION],
    unlocks: ['Shipyard foundation conditions'],
  },
  [RESEARCH_TYPES.COLONIAL_BUREAUCRACY]: {
    id: RESEARCH_TYPES.COLONIAL_BUREAUCRACY,
    name: 'Colonial Bureaucracy',
    branch: RESEARCH_CATEGORIES.GOVERNANCE,
    category: RESEARCH_CATEGORIES.GOVERNANCE,
    tier: 2,
    description: 'Defines the records and authority needed to govern an additional city.',
    cost: 3200,
    durationSeconds: 7200,
    requirements: [RESEARCH_TYPES.TAX_RECORDS],
    unlocks: ['Palace level 1 conditions'],
  },
  [RESEARCH_TYPES.ORGANIZED_LABOR]: {
    id: RESEARCH_TYPES.ORGANIZED_LABOR,
    name: 'Organized Labor',
    branch: RESEARCH_CATEGORIES.ECONOMY,
    category: RESEARCH_CATEGORIES.ECONOMY,
    tier: 2,
    description: 'Improves worker planning for stronger production and upgrade scaling.',
    cost: 3200,
    durationSeconds: 7200,
    requirements: [RESEARCH_TYPES.IMPROVED_WOODCUTTING],
    unlocks: ['Worker efficiency milestones', 'City Hall level 15 conditions'],
  },
  [RESEARCH_TYPES.TAX_RECORDS]: {
    id: RESEARCH_TYPES.TAX_RECORDS,
    name: 'Tax Records',
    branch: RESEARCH_CATEGORIES.GOVERNANCE,
    category: RESEARCH_CATEGORIES.GOVERNANCE,
    tier: 2,
    description: 'Improves administrative control and prepares the city for higher governance tiers.',
    cost: 3200,
    durationSeconds: 7200,
    requirements: [RESEARCH_TYPES.ORGANIZED_LABOR],
    unlocks: ['City Hall level 20 conditions', 'Palace progression'],
  },
  [RESEARCH_TYPES.MARKET_EXCHANGE]: {
    id: RESEARCH_TYPES.MARKET_EXCHANGE,
    name: 'Market Exchange',
    branch: RESEARCH_CATEGORIES.TRADE,
    category: RESEARCH_CATEGORIES.TRADE,
    tier: 2,
    description: 'Unlocks structured commerce and better Trading Post progression.',
    cost: 3200,
    durationSeconds: 7200,
    requirements: [RESEARCH_TYPES.BASIC_TRADE],
    unlocks: ['Trading Post level 20 conditions', 'Commerce bonuses'],
  },
  [RESEARCH_TYPES.FORMATION_TACTICS]: {
    id: RESEARCH_TYPES.FORMATION_TACTICS,
    name: 'Formation Tactics',
    branch: RESEARCH_CATEGORIES.MILITARY,
    category: RESEARCH_CATEGORIES.MILITARY,
    tier: 2,
    description: 'Formalizes battlefield organization and unlocks stronger unit conditions.',
    cost: 3200,
    durationSeconds: 7200,
    requirements: [RESEARCH_TYPES.BASIC_TRAINING],
    unlocks: ['Swordsman doctrine', 'Barracks level 10 conditions'],
  },
  [RESEARCH_TYPES.MILITARY_LOGISTICS]: {
    id: RESEARCH_TYPES.MILITARY_LOGISTICS,
    name: 'Military Logistics',
    branch: RESEARCH_CATEGORIES.MILITARY,
    category: RESEARCH_CATEGORIES.MILITARY,
    tier: 2,
    description: 'Coordinates supply, muster areas, and equipment handling for a stronger barracks.',
    cost: 3200,
    durationSeconds: 7200,
    requirements: [RESEARCH_TYPES.FORMATION_TACTICS],
    unlocks: ['Barracks level 3 conditions'],
  },
  [RESEARCH_TYPES.RANGED_DRILLS]: {
    id: RESEARCH_TYPES.RANGED_DRILLS,
    name: 'Ranged Drills',
    branch: RESEARCH_CATEGORIES.MILITARY,
    category: RESEARCH_CATEGORIES.MILITARY,
    tier: 2,
    description: 'Trains bow crews separately from general infantry formations.',
    cost: 3200,
    durationSeconds: 7200,
    requirements: [RESEARCH_TYPES.FORMATION_TACTICS],
    unlocks: ['Archer training'],
  },
  [RESEARCH_TYPES.IRON_WEAPONS]: {
    id: RESEARCH_TYPES.IRON_WEAPONS,
    name: 'Iron Weapons',
    branch: RESEARCH_CATEGORIES.MILITARY,
    category: RESEARCH_CATEGORIES.MILITARY,
    tier: 3,
    description: 'Improves weapon quality for advanced infantry and cavalry paths.',
    cost: 8200,
    durationSeconds: 21600,
    requirements: [RESEARCH_TYPES.FORMATION_TACTICS],
    unlocks: ['Cavalry doctrine', 'Elite land unit conditions'],
  },
  [RESEARCH_TYPES.STEEL_WEAPONS]: {
    id: RESEARCH_TYPES.STEEL_WEAPONS,
    name: 'Steel Weapons',
    branch: RESEARCH_CATEGORIES.MILITARY,
    category: RESEARCH_CATEGORIES.MILITARY,
    tier: 3,
    description: 'Refines blades and armor fittings for trained swordsmen.',
    cost: 8200,
    durationSeconds: 21600,
    requirements: [RESEARCH_TYPES.IRON_WEAPONS],
    unlocks: ['Swordsman training'],
  },
  [RESEARCH_TYPES.MOUNTED_WARFARE]: {
    id: RESEARCH_TYPES.MOUNTED_WARFARE,
    name: 'Mounted Warfare',
    branch: RESEARCH_CATEGORIES.MILITARY,
    category: RESEARCH_CATEGORIES.MILITARY,
    tier: 3,
    description: 'Establishes cavalry tactics, stables, and wine-supported upkeep planning.',
    cost: 8200,
    durationSeconds: 21600,
    requirements: [RESEARCH_TYPES.IRON_WEAPONS, RESEARCH_TYPES.MARKET_EXCHANGE],
    unlocks: ['Cavalry training'],
  },
  [RESEARCH_TYPES.SIEGE_ENGINEERING]: {
    id: RESEARCH_TYPES.SIEGE_ENGINEERING,
    name: 'Siege Engineering',
    branch: RESEARCH_CATEGORIES.MILITARY,
    category: RESEARCH_CATEGORIES.MILITARY,
    tier: 4,
    description: 'Unlocks heavy battlefield machinery and late Barracks progression.',
    cost: 16500,
    durationSeconds: 43200,
    requirements: [RESEARCH_TYPES.IRON_WEAPONS, RESEARCH_TYPES.ENGINEERING_PLANS],
    unlocks: ['Catapult improvements', 'Siege milestone conditions'],
  },
  [RESEARCH_TYPES.SIEGE_LOGISTICS]: {
    id: RESEARCH_TYPES.SIEGE_LOGISTICS,
    name: 'Siege Logistics',
    branch: RESEARCH_CATEGORIES.MILITARY,
    category: RESEARCH_CATEGORIES.MILITARY,
    tier: 4,
    description: 'Plans the workshops, crews, and transport needed for field siege engines.',
    cost: 16500,
    durationSeconds: 43200,
    requirements: [RESEARCH_TYPES.SIEGE_ENGINEERING, RESEARCH_TYPES.WALL_ENGINEERING],
    unlocks: ['Catapult training'],
  },
  [RESEARCH_TYPES.SHIPBUILDING]: {
    id: RESEARCH_TYPES.SHIPBUILDING,
    name: 'Shipbuilding',
    branch: RESEARCH_CATEGORIES.NAVAL,
    category: RESEARCH_CATEGORIES.NAVAL,
    tier: 2,
    description: 'Standardizes military ship construction and Shipyard scaling.',
    cost: 3200,
    durationSeconds: 7200,
    requirements: [RESEARCH_TYPES.BASIC_NAVIGATION],
    unlocks: ['Shipyard level 10 conditions', 'Light warship progression'],
  },
  [RESEARCH_TYPES.COASTAL_PATROLS]: {
    id: RESEARCH_TYPES.COASTAL_PATROLS,
    name: 'Coastal Patrols',
    branch: RESEARCH_CATEGORIES.NAVAL,
    category: RESEARCH_CATEGORIES.NAVAL,
    tier: 2,
    description: 'Trains crews for basic coastal warship patrols.',
    cost: 3200,
    durationSeconds: 7200,
    requirements: [RESEARCH_TYPES.SHIPBUILDING],
    unlocks: ['Light Ship training'],
  },
  [RESEARCH_TYPES.LIGHT_GALLEY_HANDLING]: {
    id: RESEARCH_TYPES.LIGHT_GALLEY_HANDLING,
    name: 'Light Galley Handling',
    branch: RESEARCH_CATEGORIES.NAVAL,
    category: RESEARCH_CATEGORIES.NAVAL,
    tier: 2,
    description: 'Specializes crews for fast galley movement and patrol duty.',
    cost: 3200,
    durationSeconds: 7200,
    requirements: [RESEARCH_TYPES.SHIPBUILDING],
    unlocks: ['Light Galley training'],
  },
  [RESEARCH_TYPES.DOCKSIDE_BOARDING]: {
    id: RESEARCH_TYPES.DOCKSIDE_BOARDING,
    name: 'Dockside Boarding',
    branch: RESEARCH_CATEGORIES.NAVAL,
    category: RESEARCH_CATEGORIES.NAVAL,
    tier: 2,
    description: 'Prepares marines and boarding gear for close-range naval raids.',
    cost: 3200,
    durationSeconds: 7200,
    requirements: [RESEARCH_TYPES.SHIPBUILDING],
    unlocks: ['Boarding Skiff training'],
  },
  [RESEARCH_TYPES.RAM_SHIP_DESIGN]: {
    id: RESEARCH_TYPES.RAM_SHIP_DESIGN,
    name: 'Ram Ship Design',
    branch: RESEARCH_CATEGORIES.NAVAL,
    category: RESEARCH_CATEGORIES.NAVAL,
    tier: 2,
    description: 'Develops reinforced rams and heavier defensive ship frames.',
    cost: 3200,
    durationSeconds: 7200,
    requirements: [RESEARCH_TYPES.SHIPBUILDING],
    unlocks: ['Ram Ship training'],
  },
  [RESEARCH_TYPES.FLEET_LOGISTICS]: {
    id: RESEARCH_TYPES.FLEET_LOGISTICS,
    name: 'Fleet Logistics',
    branch: RESEARCH_CATEGORIES.NAVAL,
    category: RESEARCH_CATEGORIES.NAVAL,
    tier: 2,
    description: 'Coordinates shipyard supply chains for medium fleet construction.',
    cost: 3200,
    durationSeconds: 7200,
    requirements: [RESEARCH_TYPES.SHIPBUILDING],
    unlocks: ['Shipyard level 3 conditions'],
  },
  [RESEARCH_TYPES.REINFORCED_HULLS]: {
    id: RESEARCH_TYPES.REINFORCED_HULLS,
    name: 'Reinforced Hulls',
    branch: RESEARCH_CATEGORIES.NAVAL,
    category: RESEARCH_CATEGORIES.NAVAL,
    tier: 3,
    description: 'Improves warship durability and unlocks medium naval construction.',
    cost: 8200,
    durationSeconds: 21600,
    requirements: [RESEARCH_TYPES.SHIPBUILDING],
    unlocks: ['War Galley conditions', 'Shipyard level 20 conditions'],
  },
  [RESEARCH_TYPES.WAR_GALLEY_DESIGN]: {
    id: RESEARCH_TYPES.WAR_GALLEY_DESIGN,
    name: 'War Galley Design',
    branch: RESEARCH_CATEGORIES.NAVAL,
    category: RESEARCH_CATEGORIES.NAVAL,
    tier: 3,
    description: 'Turns reinforced hull theory into a balanced line warship plan.',
    cost: 8200,
    durationSeconds: 21600,
    requirements: [RESEARCH_TYPES.REINFORCED_HULLS],
    unlocks: ['War Galley training'],
  },
  [RESEARCH_TYPES.NAVAL_TACTICS]: {
    id: RESEARCH_TYPES.NAVAL_TACTICS,
    name: 'Naval Tactics',
    branch: RESEARCH_CATEGORIES.NAVAL,
    category: RESEARCH_CATEGORIES.NAVAL,
    tier: 4,
    description: 'Unlocks organized sea combat and late warship command paths.',
    cost: 16500,
    durationSeconds: 43200,
    requirements: [RESEARCH_TYPES.REINFORCED_HULLS],
    unlocks: ['Fire Ship conditions', 'Heavy Warship conditions'],
  },
  [RESEARCH_TYPES.NAVAL_ARTILLERY]: {
    id: RESEARCH_TYPES.NAVAL_ARTILLERY,
    name: 'Naval Artillery',
    branch: RESEARCH_CATEGORIES.NAVAL,
    category: RESEARCH_CATEGORIES.NAVAL,
    tier: 3,
    description: 'Adapts crystal-guided optics and rangefinding to ship-mounted ballistae.',
    cost: 8200,
    durationSeconds: 21600,
    requirements: [RESEARCH_TYPES.CRYSTAL_OPTICS],
    unlocks: ['Ballista Ship training'],
  },
  [RESEARCH_TYPES.INCENDIARY_SHIPBUILDING]: {
    id: RESEARCH_TYPES.INCENDIARY_SHIPBUILDING,
    name: 'Incendiary Shipbuilding',
    branch: RESEARCH_CATEGORIES.NAVAL,
    category: RESEARCH_CATEGORIES.NAVAL,
    tier: 4,
    description: 'Controls sulfur-heavy fire systems for high-risk assault ships.',
    cost: 16500,
    durationSeconds: 43200,
    requirements: [RESEARCH_TYPES.NAVAL_TACTICS],
    unlocks: ['Fire Ship training'],
  },
  [RESEARCH_TYPES.HEAVY_SHIPWRIGHTING]: {
    id: RESEARCH_TYPES.HEAVY_SHIPWRIGHTING,
    name: 'Heavy Shipwrighting',
    branch: RESEARCH_CATEGORIES.NAVAL,
    category: RESEARCH_CATEGORIES.NAVAL,
    tier: 4,
    description: 'Builds the command structure and hull plans needed for heavy warships.',
    cost: 16500,
    durationSeconds: 43200,
    requirements: [RESEARCH_TYPES.NAVAL_TACTICS],
    unlocks: ['Heavy Warship training'],
  },
  [RESEARCH_TYPES.STONE_MASONRY]: {
    id: RESEARCH_TYPES.STONE_MASONRY,
    name: 'Stone Masonry',
    branch: RESEARCH_CATEGORIES.CONSTRUCTION,
    category: RESEARCH_CATEGORIES.CONSTRUCTION,
    tier: 2,
    description: 'Introduces marble-heavy construction for advanced civic upgrades.',
    cost: 3200,
    durationSeconds: 7200,
    requirements: [RESEARCH_TYPES.BASIC_ARCHITECTURE],
    unlocks: ['Marble upgrade conditions', 'Wall level 15 conditions'],
  },
  [RESEARCH_TYPES.ENGINEERING_PLANS]: {
    id: RESEARCH_TYPES.ENGINEERING_PLANS,
    name: 'Engineering Plans',
    branch: RESEARCH_CATEGORIES.CONSTRUCTION,
    category: RESEARCH_CATEGORIES.CONSTRUCTION,
    tier: 3,
    description: 'Coordinates large building works and advanced siege machinery.',
    cost: 8200,
    durationSeconds: 21600,
    requirements: [RESEARCH_TYPES.STONE_MASONRY],
    unlocks: ['Building level 30 conditions', 'Siege Engineering path'],
  },
  [RESEARCH_TYPES.CRYSTAL_OPTICS]: {
    id: RESEARCH_TYPES.CRYSTAL_OPTICS,
    name: 'Crystal Optics',
    branch: RESEARCH_CATEGORIES.SCIENCE,
    category: RESEARCH_CATEGORIES.SCIENCE,
    tier: 3,
    description: 'Uses crystal tools to improve research precision and naval artillery.',
    cost: 8200,
    durationSeconds: 21600,
    requirements: [RESEARCH_TYPES.BASIC_STORAGE],
    unlocks: ['Ballista Ship conditions', 'Academy level 25 conditions'],
  },
  [RESEARCH_TYPES.ADMINISTRATION]: {
    id: RESEARCH_TYPES.ADMINISTRATION,
    name: 'Administration',
    branch: RESEARCH_CATEGORIES.GOVERNANCE,
    category: RESEARCH_CATEGORIES.GOVERNANCE,
    tier: 3,
    description: 'Improves empire control for Palace and Governor Residency milestones.',
    cost: 8200,
    durationSeconds: 21600,
    requirements: [RESEARCH_TYPES.TAX_RECORDS],
    unlocks: ['Palace level 30 conditions', 'Governor progression'],
  },
  [RESEARCH_TYPES.WALL_ENGINEERING]: {
    id: RESEARCH_TYPES.WALL_ENGINEERING,
    name: 'Wall Engineering',
    branch: RESEARCH_CATEGORIES.DEFENSE,
    category: RESEARCH_CATEGORIES.DEFENSE,
    tier: 3,
    description: 'Strengthens city defenses and unlocks advanced wall milestones.',
    cost: 8200,
    durationSeconds: 21600,
    requirements: [RESEARCH_TYPES.STONE_MASONRY],
    unlocks: ['Town Wall level 25 conditions', 'Defensive capstones'],
  },
  [RESEARCH_TYPES.LUXURY_REFINEMENT]: {
    id: RESEARCH_TYPES.LUXURY_REFINEMENT,
    name: 'Luxury Refinement',
    branch: RESEARCH_CATEGORIES.LUXURY,
    category: RESEARCH_CATEGORIES.LUXURY,
    tier: 2,
    description: 'Improves extraction and prepares luxury resources for advanced costs.',
    cost: 3200,
    durationSeconds: 7200,
    requirements: [RESEARCH_TYPES.BASIC_STORAGE],
    unlocks: ['Luxury Extractor level 15 conditions', 'Advanced resource recipes'],
  },
  [RESEARCH_TYPES.COUNTERINTELLIGENCE]: {
    id: RESEARCH_TYPES.COUNTERINTELLIGENCE,
    name: 'Counterintelligence',
    branch: RESEARCH_CATEGORIES.ESPIONAGE,
    category: RESEARCH_CATEGORIES.ESPIONAGE,
    tier: 2,
    description: 'Prepares the empire for future spy defense and hidden threat systems.',
    cost: 3200,
    durationSeconds: 7200,
    requirements: [RESEARCH_TYPES.ADMINISTRATION],
    unlocks: ['Future espionage defenses', 'Governance security milestones'],
  },
} as const;
