export const RESEARCH_PRODUCTION_CONFIG = {
  researchPerScientistPerHour: 4,
  academyBonusPerLevelAboveOne: 0.1,
} as const;

export const RESEARCH_CATEGORIES = {
  ECONOMY: 'economy',
  MILITARY: 'military',
  NAVAL: 'naval',
  CONSTRUCTION: 'construction',
  SCIENCE: 'science',
  GOVERNANCE: 'governance',
  TRADE: 'trade',
  DEFENSE: 'defense',
  LUXURY: 'luxury',
  ESPIONAGE: 'espionage',
} as const;

export type ResearchCategory = (typeof RESEARCH_CATEGORIES)[keyof typeof RESEARCH_CATEGORIES];

export const RESEARCH_TYPES = {
  IMPROVED_WOODCUTTING: 'improved_woodcutting',
  BASIC_STORAGE: 'basic_storage',
  BASIC_ARCHITECTURE: 'basic_architecture',
  BASIC_NAVIGATION: 'basic_navigation',
  BASIC_TRAINING: 'basic_training',
  BASIC_TRADE: 'basic_trade',
  ORGANIZED_LABOR: 'organized_labor',
  TAX_RECORDS: 'tax_records',
  MARKET_EXCHANGE: 'market_exchange',
  FORMATION_TACTICS: 'formation_tactics',
  IRON_WEAPONS: 'iron_weapons',
  SIEGE_ENGINEERING: 'siege_engineering',
  SHIPBUILDING: 'shipbuilding',
  REINFORCED_HULLS: 'reinforced_hulls',
  NAVAL_TACTICS: 'naval_tactics',
  STONE_MASONRY: 'stone_masonry',
  ENGINEERING_PLANS: 'engineering_plans',
  CRYSTAL_OPTICS: 'crystal_optics',
  ADMINISTRATION: 'administration',
  WALL_ENGINEERING: 'wall_engineering',
  LUXURY_REFINEMENT: 'luxury_refinement',
  COUNTERINTELLIGENCE: 'counterintelligence',
} as const;

export type TechnologyId = (typeof RESEARCH_TYPES)[keyof typeof RESEARCH_TYPES];

export type TechnologyDefinition = {
  id: TechnologyId;
  name: string;
  branch: ResearchCategory;
  category: ResearchCategory;
  tier: number;
  description: string;
  cost: number;
  durationSeconds: number;
  requirements: TechnologyId[];
  unlocks: string[];
};

export const TECHNOLOGY_CONFIG: Record<TechnologyId, TechnologyDefinition> = {
  [RESEARCH_TYPES.IMPROVED_WOODCUTTING]: {
    id: RESEARCH_TYPES.IMPROVED_WOODCUTTING,
    name: 'Improved Woodcutting',
    branch: RESEARCH_CATEGORIES.ECONOMY,
    category: RESEARCH_CATEGORIES.ECONOMY,
    tier: 1,
    description: 'Improves wood production. The bonus will be applied in a future sprint.',
    cost: 50,
    durationSeconds: 60,
    requirements: [],
    unlocks: ['Economy upgrade conditions', 'Higher Warehouse progression'],
  },
  [RESEARCH_TYPES.BASIC_STORAGE]: {
    id: RESEARCH_TYPES.BASIC_STORAGE,
    name: 'Basic Storage',
    branch: RESEARCH_CATEGORIES.ECONOMY,
    category: RESEARCH_CATEGORIES.ECONOMY,
    tier: 1,
    description: 'Improves storage knowledge. Advanced storage bonuses will be added later.',
    cost: 75,
    durationSeconds: 90,
    requirements: [],
    unlocks: ['Warehouse milestones', 'Larger resource stockpiles'],
  },
  [RESEARCH_TYPES.BASIC_ARCHITECTURE]: {
    id: RESEARCH_TYPES.BASIC_ARCHITECTURE,
    name: 'Basic Architecture',
    branch: RESEARCH_CATEGORIES.CONSTRUCTION,
    category: RESEARCH_CATEGORIES.CONSTRUCTION,
    tier: 1,
    description: 'Unlocks better construction planning. Construction bonuses will be added later.',
    cost: 100,
    durationSeconds: 120,
    requirements: [RESEARCH_TYPES.IMPROVED_WOODCUTTING],
    unlocks: ['Building level 10 progression', 'Advanced construction conditions'],
  },
  [RESEARCH_TYPES.BASIC_NAVIGATION]: {
    id: RESEARCH_TYPES.BASIC_NAVIGATION,
    name: 'Basic Navigation',
    branch: RESEARCH_CATEGORIES.NAVAL,
    category: RESEARCH_CATEGORIES.NAVAL,
    tier: 1,
    description: 'Prepares the empire for ships and future expansion.',
    cost: 100,
    durationSeconds: 120,
    requirements: [],
    unlocks: ['Port upgrades', 'Shipyard foundation'],
  },
  [RESEARCH_TYPES.BASIC_TRAINING]: {
    id: RESEARCH_TYPES.BASIC_TRAINING,
    name: 'Basic Training',
    branch: RESEARCH_CATEGORIES.MILITARY,
    category: RESEARCH_CATEGORIES.MILITARY,
    tier: 1,
    description: 'Prepares the city for basic unit training in a future sprint.',
    cost: 100,
    durationSeconds: 120,
    requirements: [],
    unlocks: ['Barracks progression', 'Core infantry training'],
  },
  [RESEARCH_TYPES.BASIC_TRADE]: {
    id: RESEARCH_TYPES.BASIC_TRADE,
    name: 'Basic Trade',
    branch: RESEARCH_CATEGORIES.TRADE,
    category: RESEARCH_CATEGORIES.TRADE,
    tier: 1,
    description: 'Prepares the city for future marketplace and trade routes.',
    cost: 125,
    durationSeconds: 150,
    requirements: [RESEARCH_TYPES.BASIC_NAVIGATION],
    unlocks: ['Trading Post conditions', 'Commerce upgrades'],
  },
  [RESEARCH_TYPES.ORGANIZED_LABOR]: {
    id: RESEARCH_TYPES.ORGANIZED_LABOR,
    name: 'Organized Labor',
    branch: RESEARCH_CATEGORIES.ECONOMY,
    category: RESEARCH_CATEGORIES.ECONOMY,
    tier: 2,
    description: 'Improves worker planning for stronger production and upgrade scaling.',
    cost: 180,
    durationSeconds: 210,
    requirements: [RESEARCH_TYPES.IMPROVED_WOODCUTTING],
    unlocks: ['Worker efficiency milestones', 'City Hall level 15 conditions'],
  },
  [RESEARCH_TYPES.TAX_RECORDS]: {
    id: RESEARCH_TYPES.TAX_RECORDS,
    name: 'Tax Records',
    branch: RESEARCH_CATEGORIES.GOVERNANCE,
    category: RESEARCH_CATEGORIES.GOVERNANCE,
    tier: 2,
    description: 'Improves administrative control and prepares the city for higher governance tiers.',
    cost: 220,
    durationSeconds: 240,
    requirements: [RESEARCH_TYPES.ORGANIZED_LABOR],
    unlocks: ['City Hall level 20 conditions', 'Palace progression'],
  },
  [RESEARCH_TYPES.MARKET_EXCHANGE]: {
    id: RESEARCH_TYPES.MARKET_EXCHANGE,
    name: 'Market Exchange',
    branch: RESEARCH_CATEGORIES.TRADE,
    category: RESEARCH_CATEGORIES.TRADE,
    tier: 2,
    description: 'Unlocks structured commerce and better Trading Post progression.',
    cost: 260,
    durationSeconds: 270,
    requirements: [RESEARCH_TYPES.BASIC_TRADE],
    unlocks: ['Trading Post level 20 conditions', 'Commerce bonuses'],
  },
  [RESEARCH_TYPES.FORMATION_TACTICS]: {
    id: RESEARCH_TYPES.FORMATION_TACTICS,
    name: 'Formation Tactics',
    branch: RESEARCH_CATEGORIES.MILITARY,
    category: RESEARCH_CATEGORIES.MILITARY,
    tier: 2,
    description: 'Formalizes battlefield organization and unlocks stronger unit conditions.',
    cost: 200,
    durationSeconds: 240,
    requirements: [RESEARCH_TYPES.BASIC_TRAINING],
    unlocks: ['Swordsman doctrine', 'Barracks level 10 conditions'],
  },
  [RESEARCH_TYPES.IRON_WEAPONS]: {
    id: RESEARCH_TYPES.IRON_WEAPONS,
    name: 'Iron Weapons',
    branch: RESEARCH_CATEGORIES.MILITARY,
    category: RESEARCH_CATEGORIES.MILITARY,
    tier: 3,
    description: 'Improves weapon quality for advanced infantry and cavalry paths.',
    cost: 340,
    durationSeconds: 360,
    requirements: [RESEARCH_TYPES.FORMATION_TACTICS],
    unlocks: ['Cavalry doctrine', 'Elite land unit conditions'],
  },
  [RESEARCH_TYPES.SIEGE_ENGINEERING]: {
    id: RESEARCH_TYPES.SIEGE_ENGINEERING,
    name: 'Siege Engineering',
    branch: RESEARCH_CATEGORIES.MILITARY,
    category: RESEARCH_CATEGORIES.MILITARY,
    tier: 4,
    description: 'Unlocks heavy battlefield machinery and late Barracks progression.',
    cost: 520,
    durationSeconds: 540,
    requirements: [RESEARCH_TYPES.IRON_WEAPONS, RESEARCH_TYPES.ENGINEERING_PLANS],
    unlocks: ['Catapult improvements', 'Siege milestone conditions'],
  },
  [RESEARCH_TYPES.SHIPBUILDING]: {
    id: RESEARCH_TYPES.SHIPBUILDING,
    name: 'Shipbuilding',
    branch: RESEARCH_CATEGORIES.NAVAL,
    category: RESEARCH_CATEGORIES.NAVAL,
    tier: 2,
    description: 'Standardizes military ship construction and Shipyard scaling.',
    cost: 220,
    durationSeconds: 240,
    requirements: [RESEARCH_TYPES.BASIC_NAVIGATION],
    unlocks: ['Shipyard level 10 conditions', 'Light warship progression'],
  },
  [RESEARCH_TYPES.REINFORCED_HULLS]: {
    id: RESEARCH_TYPES.REINFORCED_HULLS,
    name: 'Reinforced Hulls',
    branch: RESEARCH_CATEGORIES.NAVAL,
    category: RESEARCH_CATEGORIES.NAVAL,
    tier: 3,
    description: 'Improves warship durability and unlocks medium naval construction.',
    cost: 360,
    durationSeconds: 390,
    requirements: [RESEARCH_TYPES.SHIPBUILDING],
    unlocks: ['War Galley conditions', 'Shipyard level 20 conditions'],
  },
  [RESEARCH_TYPES.NAVAL_TACTICS]: {
    id: RESEARCH_TYPES.NAVAL_TACTICS,
    name: 'Naval Tactics',
    branch: RESEARCH_CATEGORIES.NAVAL,
    category: RESEARCH_CATEGORIES.NAVAL,
    tier: 4,
    description: 'Unlocks organized sea combat and late warship command paths.',
    cost: 560,
    durationSeconds: 600,
    requirements: [RESEARCH_TYPES.REINFORCED_HULLS],
    unlocks: ['Fire Ship conditions', 'Heavy Warship conditions'],
  },
  [RESEARCH_TYPES.STONE_MASONRY]: {
    id: RESEARCH_TYPES.STONE_MASONRY,
    name: 'Stone Masonry',
    branch: RESEARCH_CATEGORIES.CONSTRUCTION,
    category: RESEARCH_CATEGORIES.CONSTRUCTION,
    tier: 2,
    description: 'Introduces marble-heavy construction for advanced civic upgrades.',
    cost: 220,
    durationSeconds: 260,
    requirements: [RESEARCH_TYPES.BASIC_ARCHITECTURE],
    unlocks: ['Marble upgrade conditions', 'Wall level 15 conditions'],
  },
  [RESEARCH_TYPES.ENGINEERING_PLANS]: {
    id: RESEARCH_TYPES.ENGINEERING_PLANS,
    name: 'Engineering Plans',
    branch: RESEARCH_CATEGORIES.CONSTRUCTION,
    category: RESEARCH_CATEGORIES.CONSTRUCTION,
    tier: 3,
    description: 'Coordinates large building works and advanced siege machinery.',
    cost: 380,
    durationSeconds: 420,
    requirements: [RESEARCH_TYPES.STONE_MASONRY],
    unlocks: ['Building level 30 conditions', 'Siege Engineering path'],
  },
  [RESEARCH_TYPES.CRYSTAL_OPTICS]: {
    id: RESEARCH_TYPES.CRYSTAL_OPTICS,
    name: 'Crystal Optics',
    branch: RESEARCH_CATEGORIES.SCIENCE,
    category: RESEARCH_CATEGORIES.SCIENCE,
    tier: 3,
    description: 'Uses crystal tools to improve research precision and naval artillery.',
    cost: 420,
    durationSeconds: 450,
    requirements: [RESEARCH_TYPES.BASIC_STORAGE],
    unlocks: ['Ballista Ship conditions', 'Academy level 25 conditions'],
  },
  [RESEARCH_TYPES.ADMINISTRATION]: {
    id: RESEARCH_TYPES.ADMINISTRATION,
    name: 'Administration',
    branch: RESEARCH_CATEGORIES.GOVERNANCE,
    category: RESEARCH_CATEGORIES.GOVERNANCE,
    tier: 3,
    description: 'Improves empire control for Palace and Governor Residency milestones.',
    cost: 440,
    durationSeconds: 480,
    requirements: [RESEARCH_TYPES.TAX_RECORDS],
    unlocks: ['Palace level 30 conditions', 'Governor progression'],
  },
  [RESEARCH_TYPES.WALL_ENGINEERING]: {
    id: RESEARCH_TYPES.WALL_ENGINEERING,
    name: 'Wall Engineering',
    branch: RESEARCH_CATEGORIES.DEFENSE,
    category: RESEARCH_CATEGORIES.DEFENSE,
    tier: 3,
    description: 'Strengthens city defenses and unlocks advanced wall milestones.',
    cost: 360,
    durationSeconds: 420,
    requirements: [RESEARCH_TYPES.STONE_MASONRY],
    unlocks: ['Town Wall level 25 conditions', 'Defensive capstones'],
  },
  [RESEARCH_TYPES.LUXURY_REFINEMENT]: {
    id: RESEARCH_TYPES.LUXURY_REFINEMENT,
    name: 'Luxury Refinement',
    branch: RESEARCH_CATEGORIES.LUXURY,
    category: RESEARCH_CATEGORIES.LUXURY,
    tier: 2,
    description: 'Improves extraction and prepares luxury resources for advanced costs.',
    cost: 260,
    durationSeconds: 300,
    requirements: [RESEARCH_TYPES.BASIC_STORAGE],
    unlocks: ['Luxury Extractor level 15 conditions', 'Advanced resource recipes'],
  },
  [RESEARCH_TYPES.COUNTERINTELLIGENCE]: {
    id: RESEARCH_TYPES.COUNTERINTELLIGENCE,
    name: 'Counterintelligence',
    branch: RESEARCH_CATEGORIES.ESPIONAGE,
    category: RESEARCH_CATEGORIES.ESPIONAGE,
    tier: 2,
    description: 'Prepares the empire for future spy defense and hidden threat systems.',
    cost: 240,
    durationSeconds: 300,
    requirements: [RESEARCH_TYPES.ADMINISTRATION],
    unlocks: ['Future espionage defenses', 'Governance security milestones'],
  },
} as const;
