import { CONDITION_TYPES, type UnlockCondition } from './conditions.config.js';
import { RESEARCH_TYPES } from './research.config.js';

export const UNIT_TYPES = {
  MILITIA: 'militia',
  SPEARMAN: 'spearman',
  ARCHER: 'archer',
  SWORDSMAN: 'swordsman',
  CAVALRY: 'cavalry',
  CATAPULT: 'catapult',
  LIGHT_SHIP: 'light_ship',
  RAM_SHIP: 'ram_ship',
  LIGHT_GALLEY: 'light_galley',
  BOARDING_SKIFF: 'boarding_skiff',
  BALLISTA_SHIP: 'ballista_ship',
  WAR_GALLEY: 'war_galley',
  FIRE_SHIP: 'fire_ship',
  HEAVY_WARSHIP: 'heavy_warship',
  SPY: 'spy',
} as const;

export type UnitType = (typeof UNIT_TYPES)[keyof typeof UNIT_TYPES];
export type UnitCategory = 'land' | 'naval' | 'spy';
export type UnitResourceCost = {
  wood: number;
  gold: number;
  marble: number;
  wine: number;
  crystal: number;
  sulfur: number;
};
export type UnitUpkeep = {
  resourceType: keyof UnitResourceCost;
  amountPerHour: number;
};

export type UnitDefinition = {
  id: UnitType;
  category: UnitCategory;
  unitClass: string;
  tier: number;
  searchTags: string[];
  name: string;
  pluralName: string;
  description: string;
  cost: UnitResourceCost;
  upkeep: UnitUpkeep;
  trainingSecondsPerUnit: number;
  attack: number;
  defense: number;
  health: number;
  speed: number;
  capacity: number;
  requiredBuildingType: string;
  requiredBuildingLevel: number;
  requiredBuildings?: Array<{
    buildingType: string;
    level: number;
  }>;
  unlockConditions?: UnlockCondition[];
};

export const UNIT_CONFIG: Record<UnitType, UnitDefinition> = {
  [UNIT_TYPES.MILITIA]: {
    id: UNIT_TYPES.MILITIA,
    category: 'land',
    unitClass: 'infantry',
    tier: 1,
    searchTags: ['land', 'infantry', 'early', 'cheap'],
    name: 'Militia',
    pluralName: 'Militia',
    description: 'Fast, cheap local defenders. Useful when you need bodies quickly.',
    cost: { wood: 25, gold: 15, marble: 0, wine: 0, crystal: 0, sulfur: 0 },
    upkeep: { resourceType: 'gold', amountPerHour: 1 },
    trainingSecondsPerUnit: 20,
    attack: 3,
    defense: 4,
    health: 7,
    speed: 8,
    capacity: 0,
    requiredBuildingType: 'barracks',
    requiredBuildingLevel: 1,
    unlockConditions: [{ type: CONDITION_TYPES.RESEARCH_REQUIRED, technologyId: RESEARCH_TYPES.BASIC_TRAINING }],
  },
  [UNIT_TYPES.SPEARMAN]: {
    id: UNIT_TYPES.SPEARMAN,
    category: 'land',
    unitClass: 'infantry',
    tier: 1,
    searchTags: ['land', 'infantry', 'defense', 'early'],
    name: 'Spearman',
    pluralName: 'Spearmen',
    description: 'Basic defensive infantry. Low cost and a good early unit.',
    cost: { wood: 40, gold: 20, marble: 0, wine: 0, crystal: 0, sulfur: 0 },
    upkeep: { resourceType: 'gold', amountPerHour: 1 },
    trainingSecondsPerUnit: 30,
    attack: 5,
    defense: 8,
    health: 10,
    speed: 7,
    capacity: 0,
    requiredBuildingType: 'barracks',
    requiredBuildingLevel: 1,
    unlockConditions: [{ type: CONDITION_TYPES.RESEARCH_REQUIRED, technologyId: RESEARCH_TYPES.BASIC_TRAINING }],
  },
  [UNIT_TYPES.ARCHER]: {
    id: UNIT_TYPES.ARCHER,
    category: 'land',
    unitClass: 'ranged',
    tier: 2,
    searchTags: ['land', 'ranged', 'attack'],
    name: 'Archer',
    pluralName: 'Archers',
    description: 'Ranged support unit. Useful against weak camps.',
    cost: { wood: 60, gold: 30, marble: 0, wine: 0, crystal: 0, sulfur: 0 },
    upkeep: { resourceType: 'wood', amountPerHour: 1 },
    trainingSecondsPerUnit: 45,
    attack: 9,
    defense: 4,
    health: 8,
    speed: 7,
    capacity: 0,
    requiredBuildingType: 'barracks',
    requiredBuildingLevel: 2,
    requiredBuildings: [{ buildingType: 'workshop', level: 1 }],
    unlockConditions: [{ type: CONDITION_TYPES.RESEARCH_REQUIRED, technologyId: RESEARCH_TYPES.RANGED_DRILLS }],
  },
  [UNIT_TYPES.SWORDSMAN]: {
    id: UNIT_TYPES.SWORDSMAN,
    category: 'land',
    unitClass: 'infantry',
    tier: 3,
    searchTags: ['land', 'infantry', 'attack', 'sulfur'],
    name: 'Swordsman',
    pluralName: 'Swordsmen',
    description: 'Stronger attack infantry. Better against stronger camps.',
    cost: { wood: 80, gold: 50, marble: 0, wine: 0, crystal: 0, sulfur: 5 },
    upkeep: { resourceType: 'sulfur', amountPerHour: 1 },
    trainingSecondsPerUnit: 60,
    attack: 12,
    defense: 8,
    health: 12,
    speed: 6,
    capacity: 0,
    requiredBuildingType: 'barracks',
    requiredBuildingLevel: 3,
    requiredBuildings: [{ buildingType: 'workshop', level: 2 }],
    unlockConditions: [{ type: CONDITION_TYPES.RESEARCH_REQUIRED, technologyId: RESEARCH_TYPES.STEEL_WEAPONS }],
  },
  [UNIT_TYPES.CAVALRY]: {
    id: UNIT_TYPES.CAVALRY,
    category: 'land',
    unitClass: 'cavalry',
    tier: 4,
    searchTags: ['land', 'cavalry', 'fast', 'wine'],
    name: 'Cavalry',
    pluralName: 'Cavalry',
    description: 'Fast elite attackers for raids and rapid response.',
    cost: { wood: 90, gold: 90, marble: 0, wine: 10, crystal: 0, sulfur: 0 },
    upkeep: { resourceType: 'wine', amountPerHour: 1 },
    trainingSecondsPerUnit: 90,
    attack: 18,
    defense: 10,
    health: 16,
    speed: 12,
    capacity: 0,
    requiredBuildingType: 'barracks',
    requiredBuildingLevel: 4,
    requiredBuildings: [
      { buildingType: 'trading_post', level: 2 },
      { buildingType: 'tavern', level: 2 },
    ],
    unlockConditions: [
      { type: CONDITION_TYPES.RESEARCH_REQUIRED, technologyId: RESEARCH_TYPES.MOUNTED_WARFARE },
    ],
  },
  [UNIT_TYPES.CATAPULT]: {
    id: UNIT_TYPES.CATAPULT,
    category: 'land',
    unitClass: 'siege',
    tier: 5,
    searchTags: ['land', 'siege', 'sulfur', 'marble'],
    name: 'Catapult',
    pluralName: 'Catapults',
    description: 'Slow siege engine with heavy attack power.',
    cost: { wood: 180, gold: 120, marble: 20, wine: 0, crystal: 0, sulfur: 25 },
    upkeep: { resourceType: 'sulfur', amountPerHour: 3 },
    trainingSecondsPerUnit: 150,
    attack: 32,
    defense: 6,
    health: 24,
    speed: 3,
    capacity: 0,
    requiredBuildingType: 'barracks',
    requiredBuildingLevel: 5,
    requiredBuildings: [
      { buildingType: 'trading_post', level: 2 },
      { buildingType: 'workshop', level: 3 },
    ],
    unlockConditions: [
      { type: CONDITION_TYPES.RESEARCH_REQUIRED, technologyId: RESEARCH_TYPES.SIEGE_LOGISTICS },
    ],
  },
  [UNIT_TYPES.LIGHT_SHIP]: {
    id: UNIT_TYPES.LIGHT_SHIP,
    category: 'naval',
    unitClass: 'light_warship',
    tier: 1,
    searchTags: ['naval', 'warship', 'fast', 'early'],
    name: 'Light Ship',
    pluralName: 'Light Ships',
    description: 'Low-cost early warship with balanced attack and defense.',
    cost: { wood: 120, gold: 80, marble: 0, wine: 0, crystal: 0, sulfur: 20 },
    upkeep: { resourceType: 'gold', amountPerHour: 3 },
    trainingSecondsPerUnit: 90,
    attack: 10,
    defense: 8,
    health: 20,
    speed: 1.2,
    capacity: 0,
    requiredBuildingType: 'shipyard',
    requiredBuildingLevel: 1,
    requiredBuildings: [{ buildingType: 'port', level: 2 }],
    unlockConditions: [{ type: CONDITION_TYPES.RESEARCH_REQUIRED, technologyId: RESEARCH_TYPES.COASTAL_PATROLS }],
  },
  [UNIT_TYPES.RAM_SHIP]: {
    id: UNIT_TYPES.RAM_SHIP,
    category: 'naval',
    unitClass: 'ram_ship',
    tier: 2,
    searchTags: ['naval', 'warship', 'defense', 'port'],
    name: 'Ram Ship',
    pluralName: 'Ram Ships',
    description: 'Sturdy frontline ship built to protect ports.',
    cost: { wood: 220, gold: 140, marble: 50, wine: 0, crystal: 0, sulfur: 60 },
    upkeep: { resourceType: 'sulfur', amountPerHour: 4 },
    trainingSecondsPerUnit: 150,
    attack: 16,
    defense: 18,
    health: 35,
    speed: 1,
    capacity: 0,
    requiredBuildingType: 'shipyard',
    requiredBuildingLevel: 2,
    requiredBuildings: [{ buildingType: 'port', level: 3 }],
    unlockConditions: [{ type: CONDITION_TYPES.RESEARCH_REQUIRED, technologyId: RESEARCH_TYPES.RAM_SHIP_DESIGN }],
  },
  [UNIT_TYPES.LIGHT_GALLEY]: {
    id: UNIT_TYPES.LIGHT_GALLEY,
    category: 'naval',
    unitClass: 'light_warship',
    tier: 1,
    searchTags: ['naval', 'warship', 'fast', 'early'],
    name: 'Light Galley',
    pluralName: 'Light Galleys',
    description: 'Fast early warship for patrols and first naval fights.',
    cost: { wood: 75, gold: 35, marble: 0, wine: 0, crystal: 0, sulfur: 5 },
    upkeep: { resourceType: 'gold', amountPerHour: 2 },
    trainingSecondsPerUnit: 40,
    attack: 9,
    defense: 5,
    health: 12,
    speed: 10,
    capacity: 10,
    requiredBuildingType: 'shipyard',
    requiredBuildingLevel: 1,
    unlockConditions: [{ type: CONDITION_TYPES.RESEARCH_REQUIRED, technologyId: RESEARCH_TYPES.LIGHT_GALLEY_HANDLING }],
  },
  [UNIT_TYPES.BOARDING_SKIFF]: {
    id: UNIT_TYPES.BOARDING_SKIFF,
    category: 'naval',
    unitClass: 'boarding_ship',
    tier: 2,
    searchTags: ['naval', 'boarding', 'raid', 'fast'],
    name: 'Boarding Skiff',
    pluralName: 'Boarding Skiffs',
    description: 'Raiding vessel built for close-range boarding attacks.',
    cost: { wood: 105, gold: 55, marble: 0, wine: 0, crystal: 0, sulfur: 10 },
    upkeep: { resourceType: 'gold', amountPerHour: 3 },
    trainingSecondsPerUnit: 55,
    attack: 14,
    defense: 7,
    health: 16,
    speed: 9,
    capacity: 15,
    requiredBuildingType: 'shipyard',
    requiredBuildingLevel: 1,
    requiredBuildings: [{ buildingType: 'port', level: 2 }],
    unlockConditions: [{ type: CONDITION_TYPES.RESEARCH_REQUIRED, technologyId: RESEARCH_TYPES.DOCKSIDE_BOARDING }],
  },
  [UNIT_TYPES.BALLISTA_SHIP]: {
    id: UNIT_TYPES.BALLISTA_SHIP,
    category: 'naval',
    unitClass: 'artillery_ship',
    tier: 3,
    searchTags: ['naval', 'ranged', 'artillery', 'crystal'],
    name: 'Ballista Ship',
    pluralName: 'Ballista Ships',
    description: 'Medium artillery ship with strong ranged naval attack.',
    cost: { wood: 150, gold: 95, marble: 0, wine: 0, crystal: 10, sulfur: 18 },
    upkeep: { resourceType: 'crystal', amountPerHour: 2 },
    trainingSecondsPerUnit: 85,
    attack: 22,
    defense: 10,
    health: 20,
    speed: 6,
    capacity: 20,
    requiredBuildingType: 'shipyard',
    requiredBuildingLevel: 2,
    requiredBuildings: [{ buildingType: 'workshop', level: 2 }],
    unlockConditions: [{ type: CONDITION_TYPES.RESEARCH_REQUIRED, technologyId: RESEARCH_TYPES.NAVAL_ARTILLERY }],
  },
  [UNIT_TYPES.WAR_GALLEY]: {
    id: UNIT_TYPES.WAR_GALLEY,
    category: 'naval',
    unitClass: 'warship',
    tier: 3,
    searchTags: ['naval', 'warship', 'balanced', 'sulfur'],
    name: 'War Galley',
    pluralName: 'War Galleys',
    description: 'Basic naval combat ship with balanced stats.',
    cost: { wood: 160, gold: 100, marble: 0, wine: 0, crystal: 0, sulfur: 15 },
    upkeep: { resourceType: 'sulfur', amountPerHour: 3 },
    trainingSecondsPerUnit: 100,
    attack: 18,
    defense: 12,
    health: 22,
    speed: 8,
    capacity: 30,
    requiredBuildingType: 'shipyard',
    requiredBuildingLevel: 3,
    requiredBuildings: [{ buildingType: 'port', level: 3 }],
    unlockConditions: [{ type: CONDITION_TYPES.RESEARCH_REQUIRED, technologyId: RESEARCH_TYPES.WAR_GALLEY_DESIGN }],
  },
  [UNIT_TYPES.FIRE_SHIP]: {
    id: UNIT_TYPES.FIRE_SHIP,
    category: 'naval',
    unitClass: 'fire_ship',
    tier: 4,
    searchTags: ['naval', 'burst', 'fire', 'sulfur'],
    name: 'Fire Ship',
    pluralName: 'Fire Ships',
    description: 'High-risk naval attacker with strong burst damage.',
    cost: { wood: 260, gold: 180, marble: 0, wine: 0, crystal: 50, sulfur: 120 },
    upkeep: { resourceType: 'sulfur', amountPerHour: 6 },
    trainingSecondsPerUnit: 210,
    attack: 28,
    defense: 10,
    health: 25,
    speed: 0.9,
    capacity: 0,
    requiredBuildingType: 'shipyard',
    requiredBuildingLevel: 4,
    requiredBuildings: [
      { buildingType: 'port', level: 4 },
      { buildingType: 'workshop', level: 3 },
    ],
    unlockConditions: [
      { type: CONDITION_TYPES.RESEARCH_REQUIRED, technologyId: RESEARCH_TYPES.INCENDIARY_SHIPBUILDING },
    ],
  },
  [UNIT_TYPES.HEAVY_WARSHIP]: {
    id: UNIT_TYPES.HEAVY_WARSHIP,
    category: 'naval',
    unitClass: 'heavy_warship',
    tier: 5,
    searchTags: ['naval', 'heavy', 'warship', 'crystal', 'sulfur'],
    name: 'Heavy Warship',
    pluralName: 'Heavy Warships',
    description: 'Late naval power for decisive sea control.',
    cost: { wood: 260, gold: 180, marble: 40, wine: 0, crystal: 20, sulfur: 40 },
    upkeep: { resourceType: 'crystal', amountPerHour: 5 },
    trainingSecondsPerUnit: 180,
    attack: 42,
    defense: 28,
    health: 42,
    speed: 5,
    capacity: 60,
    requiredBuildingType: 'shipyard',
    requiredBuildingLevel: 5,
    requiredBuildings: [
      { buildingType: 'port', level: 5 },
      { buildingType: 'barracks', level: 3 },
      { buildingType: 'workshop', level: 3 },
    ],
    unlockConditions: [{ type: CONDITION_TYPES.RESEARCH_REQUIRED, technologyId: RESEARCH_TYPES.HEAVY_SHIPWRIGHTING }],
  },
  [UNIT_TYPES.SPY]: {
    id: UNIT_TYPES.SPY,
    category: 'spy',
    unitClass: 'intelligence',
    tier: 1,
    searchTags: ['spy', 'scouting', 'intelligence'],
    name: 'Spy',
    pluralName: 'Spies',
    description: 'Gathers intelligence about other cities before combat or trade decisions.',
    cost: { wood: 80, gold: 120, marble: 0, wine: 0, crystal: 20, sulfur: 0 },
    upkeep: { resourceType: 'gold', amountPerHour: 2 },
    trainingSecondsPerUnit: 90,
    attack: 0,
    defense: 0,
    health: 1,
    speed: 12,
    capacity: 0,
    requiredBuildingType: 'spy_agency',
    requiredBuildingLevel: 1,
  },
} as const;

export const TRAINING_CONFIG = {
  baseQuantityPerOrder: 25,
  quantityPerBuildingLevel: 5,
} as const;
